apiVersion: 1

datasources:
  - name: Prometheus
    type: promethues
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
